### PR TITLE
Update Spons Section

### PR DESCRIPTION
**Pull request by probot-codes**
Added two new sponsors from last year [Quince Entertainment and Pahuja Brothers]

### CODE REVIEW

**Comment by Team-Technocracy** [comment]
Good Job !!

**Comment by Team-Technocracy** [comment]
@probot-codes Do one more thing, crop the image of pahuja brothers (cut out extra white part on top and bottom). Quince entertainment png's background is not removed, it's black, so please remove black part too and add png without background.

and download hitavada logo, add white rectangular background (like player spot) and then replace the pic.

**Comment by probot-codes** [comment]
Done Sir!

**Comment by probot-codes** [comment]
fixed issue #18

**Pull request merged**
